# Generated by Django 5.2.15 on 2026-07-08 05:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("motor", "Motor"),
                            ("pump", "Pump"),
                            ("valve", "Valve"),
                            ("sensor", "Sensor"),
                            ("plc", "PLC"),
                            ("conveyor", "Conveyor"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("installation_date", models.DateField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="assets.area",
                    ),
                ),
            ],
            options={
                "db_table": "assets",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(fields=("area", "code"), name="unique_area_asset_code")
                ],
            },
        ),
    ]
