# Generated by Django 5.2.16 on 2026-07-18 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_asset"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "metadata_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema describing supported metadata.",
                    ),
                ),
            ],
            options={
                "db_table": "asset_types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Asset-specific metadata defined by the AssetType schema.",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="assets.assettype",
            ),
        ),
    ]
