# Generated by Django 5.2.16 on 2026-07-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_assettype_asset_metadata_alter_asset_asset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="commissioned_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="last_maintenance_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("installed", "Installed"),
                    ("commissioned", "Commissioned"),
                    ("operational", "Operational"),
                    ("maintenance", "Maintenance"),
                    ("out_of_service", "Out of Service"),
                    ("retired", "Retired"),
                ],
                default="planned",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="retired_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
