# Generated by Django 5.2.16 on 2026-07-28 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0006_asset_commissioned_at_asset_last_maintenance_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustrialEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("alarm", "Alarm"),
                            ("failure", "Failure"),
                            ("warning", "Warning"),
                            ("state_change", "State Change"),
                            ("maintenance", "Maintenance"),
                            ("operational", "Operational"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_industrial_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industrial_events",
                        to="assets.asset",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_industrial_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(
                        fields=["asset", "occurred_at"], name="telemetry_i_asset_i_aff7f5_idx"
                    ),
                    models.Index(
                        fields=["event_type", "status"], name="telemetry_i_event_t_d3d45d_idx"
                    ),
                    models.Index(
                        fields=["severity", "status"], name="telemetry_i_severit_857e9c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("metric", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "quality",
                    models.CharField(
                        choices=[("good", "Good"), ("uncertain", "Uncertain"), ("bad", "Bad")],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_records",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "ordering": ("-recorded_at",),
                "indexes": [
                    models.Index(
                        fields=["asset", "metric", "recorded_at"],
                        name="telemetry_t_asset_i_9d6981_idx",
                    ),
                    models.Index(fields=["recorded_at"], name="telemetry_t_recorde_85f705_idx"),
                ],
            },
        ),
    ]
