# Generated by Django 5.2.16 on 2026-07-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="industrialevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="telemetry",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="telemetry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
