# Generated by Django 5.2.16 on 2026-07-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="object_repr",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(help_text="Affected model name", max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="auditlog",
            table="audit_logs",
        ),
    ]
