# Generated by Django 5.2.16 on 2026-07-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_auditlog_object_repr_auditlog_user_agent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(max_length=100),
        ),
    ]
