# Generated by Django 5.2.16 on 2026-08-05 05:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0006_asset_commissioned_at_asset_last_maintenance_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("telemetry", "Telemetry"),
                            ("maintenance", "Maintenance"),
                            ("failure", "Failure"),
                            ("inspection", "Inspection"),
                            ("prediction", "Prediction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField()),
                (
                    "source",
                    models.CharField(help_text="Origin domain of this event", max_length=100),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_events",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "db_table": "operational_events",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["asset", "event_type", "occurred_at"],
                        name="operational_asset_i_fae5ad_idx",
                    ),
                    models.Index(fields=["occurred_at"], name="operational_occurre_79fa37_idx"),
                ],
            },
        ),
    ]
