# apps/operational_timeline/models/operational_event.py

import uuid

from django.db import models

from apps.assets.models import Asset


class OperationalEvent(models.Model):
    """
    Represents a unified operational event generated by
    industrial assets.
    """

    class EventType(models.TextChoices):
        TELEMETRY = "telemetry", "Telemetry"
        MAINTENANCE = "maintenance", "Maintenance"
        FAILURE = "failure", "Failure"
        INSPECTION = "inspection", "Inspection"
        PREDICTION = "prediction", "Prediction"

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    asset = models.ForeignKey(
        Asset,
        on_delete=models.CASCADE,
        related_name="operational_events",
    )

    event_type = models.CharField(
        max_length=50,
        choices=EventType.choices,
    )

    title = models.CharField(
        max_length=255,
    )

    description = models.TextField(
        blank=True,
    )

    occurred_at = models.DateTimeField()

    source = models.CharField(
        max_length=100,
        help_text="Origin domain of this event",
    )

    metadata = models.JSONField(
        default=dict,
        blank=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        db_table = "operational_events"
        ordering = ["-occurred_at"]

        indexes = [
            models.Index(
                fields=[
                    "asset",
                    "event_type",
                    "occurred_at",
                ]
            ),
            models.Index(
                fields=[
                    "occurred_at",
                ]
            ),
        ]

    def __str__(self):
        return f"{self.asset} - {self.event_type}"
